### ISSUE TITLE
If a player submits a starting article too soon to the time limit, their article loads with the "waiting for other players message"

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#102]

**Comment by ritsukaBin** [comment]
got this reproduced: 

This happened when player enter the starter article at the VERY LAST second of countdown.
<img width="1440" alt="screen shot 2016-07-27 at 2 42 46 pm" src="https://cloud.githubusercontent.com/assets/20562141/17188144/e476be00-5409-11e6-8aa3-6324d59a16d8.png">

It sometimes accompanies with a glitch of #96, sometimes doesn't. (for the test that I taken screenshot of it does, in my a few other tests it doesn't)
<img width="1440" alt="screen shot 2016-07-27 at 2 43 31 pm" src="https://cloud.githubusercontent.com/assets/20562141/17188153/e7f87442-5409-11e6-99a9-761548efe79f.png">

And when player click into other link from the starter page, the "waiting" message persist but content change. 
<img width="1440" alt="screen shot 2016-07-27 at 2 43 35 pm" src="https://cloud.githubusercontent.com/assets/20562141/17188320/7ffe3a4c-540a-11e6-88f5-0a59744ba02a.png">
<img width="1440" alt="screen shot 2016-07-27 at 2 43 40 pm" src="https://cloud.githubusercontent.com/assets/20562141/17188321/849aede8-540a-11e6-8b54-0f95c3206d90.png">


PS: timing seems to be the key to trigger this, that player needs to be precisely click enter in the VERY LAST SECOND.
