### ISSUE TITLE
Selecting an article title mid-game causes the game to generate a "waiting for other players" message with that article title

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#103]
This is generated above the actual article that was requested.

**Comment by esalling23** [comment]
@mattwbenson more information on this please! what do you mean "selecting an article title mid-game"

**Comment by mattwbenson** [comment]
Like, when you just select an article normally in the game, clicking on a
hyperlink.

**Comment by esalling23** [comment]
does this happen every time? i cannot reproduce - what do you mean mid-game? is that after the countdown is halfway complete?

**Comment by mattwbenson** [comment]
It only started happening after the new build--by mid-game, I just mean it
happens after players pick starting stocks and the race has started.

**Comment by mattwbenson** [comment]
Starting articles, sorry, on my phone.

**Comment by esalling23** [comment]
no worries! still cannot reproduce - if this shows up again please reopen issue with list of steps taken and screenshots! tested on both QA and local staging server
