### ISSUE TITLE
WG: Players are not ranked correctly

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#106]
Multiple times now, when playing on the iPad and my samsung Tablet, the player that finishes first is listed in second place, even though the game seems to be properly recording times. 
![screen shot 2016-07-28 at 10 45 09 am](https://cloud.githubusercontent.com/assets/12397944/17216920/946e6190-54b0-11e6-9caa-baeffbcb645d.png)
![screen shot 2016-07-28 at 10 45 12 am](https://cloud.githubusercontent.com/assets/12397944/17216922/959aa75e-54b0-11e6-8b38-70b27dfa7fc6.png)

**Comment by mattwbenson** [comment]
This is a two-player game, to clarify.

**Comment by esalling23** [comment]
fixed in next build
