### ISSUE TITLE
Tabbing out of hub screen during results causes multiple pages to load at once

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#108]
![screen shot 2016-07-28 at 11 11 01 am](https://cloud.githubusercontent.com/assets/12397944/17217958/25605804-54b4-11e6-8a8e-871afdf23aeb.png)
![screen shot 2016-07-28 at 11 11 06 am](https://cloud.githubusercontent.com/assets/12397944/17217961/278c01f0-54b4-11e6-99ec-dad3ff87d836.png)

**Comment by mattwbenson** [comment]
I tabbed out of the results screen in the middle of the first players' click map, and then instead of showing second and third place, it showed first place again, then second, then showed third place while the leaderboard was showing.

**Comment by esalling23** [comment]
closing until reproduced
