### ISSUE TITLE
If a player refreshes their page, it breaks the game

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#11]
Was submitting hashtags, submitted player 1's hashtag and refreshed the page. Moderator page suddenly went back to first hashtag as if a new game had just started. Player 2's page didn't change, so I tried submitting a hashtag through it. This caused the results page for the first hashtag to display, but with the player-submitted options from the original tweet, the correct answer for the first tweet, and a hashtag "#screen" that wasn't entered by either player.

**Comment by mattwbenson** [comment]
This also removed the original two players from the game session's scoreboard

**Comment by jpailthorpe** [comment]
This was you refreshing the player page right?

**Comment by mattwbenson** [comment]
Yep.
