### ISSUE TITLE
HTYI: Game is never-ending, ignores config in Keystone

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#113]
Right now in keystone HTYI is set to have 3 rounds, but my current game hasn't ended yet after at least six.

**Comment by beccachairin** [comment]
I'm still playing as well, probably upwards of 20 rounds! I assumed there was supposed to be an option to end the game manually somewhere on the main page, I didn't know it was set to end after a certain number of rounds.

**Comment by beccachairin** [comment]
update: I just continued to play but game got disconnected without an ending score screen, it's stuck on the 0 countdown. 
![screen shot 2016-08-01 at 2 08 39 pm](https://cloud.githubusercontent.com/assets/20775665/17304061/a105f9ec-57f1-11e6-84f7-c416ba6aed9d.png)
![screen shot 2016-08-01 at 2 08 10 pm](https://cloud.githubusercontent.com/assets/20775665/17304063/a5df932e-57f1-11e6-9976-154613234480.png)
