### ISSUE TITLE
HTYI: player icon links broken when group screen gets refreshed

### ISSUE THREAD

**Issue by beccachairin** [engagementgamelab/emerging-citizens#117]
Have been playing all afternoon then all of a sudden I started a few new games and none of the icons were appearing. 
![screen shot 2016-08-01 at 2 49 37 pm](https://cloud.githubusercontent.com/assets/20775665/17305557/eea20680-57f8-11e6-896e-003678e5fb6b.png)
![screen shot 2016-08-01 at 2 48 35 pm](https://cloud.githubusercontent.com/assets/20775665/17305556/eea1abea-57f8-11e6-882b-baa9eb794bd5.png)
![screen shot 2016-08-01 at 2 14 54 pm](https://cloud.githubusercontent.com/assets/20775665/17305558/eeabe826-57f8-11e6-8806-a99aa57b91d1.png)
![screen shot 2016-08-01 at 2 14 11 pm](https://cloud.githubusercontent.com/assets/20775665/17305555/eea16acc-57f8-11e6-9a0e-b7f4c7077330.png)
![screen shot 2016-08-01 at 2 13 47 pm](https://cloud.githubusercontent.com/assets/20775665/17305554/eea15f5a-57f8-11e6-98f7-ef13a063e8ca.png)

**Comment by mattwbenson** [comment]
This seems to happen if the game gets refreshed and a new game is started with an old lobby code.

**Comment by esalling23** [comment]
please reproduce and provide steps! order of logging in etc would be extremely useful, also taking note of who is being reloaded first (group vs. player)

**Comment by jpailthorpe** [comment]
"This seems to happen if the game gets refreshed and a new game is started with an old lobby code."

Same on group screen refresh. Will check this a few times once Johnny confirms.
