### ISSUE TITLE
HTYI: Desktop Players kicked from game during submission

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#119]
I had six of my eight players in a desktop window, and all six were kicked from the game. When I tried to reload the pages, all came back with a broken login page: 
![capture1](https://cloud.githubusercontent.com/assets/12397944/17306861/320ea980-5800-11e6-8751-60d722cbe18e.PNG)

**Comment by jpailthorpe** [comment]
closing due to lack of context. Will catch again if a larger issue
