### ISSUE TITLE
HTYI: Voting doesn't end even after all players have voted

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#120]
In an 8 player game, after all 8 players have voted, the round only ends when the timer runs out.

**Comment by esalling23** [comment]
cannot reproduce, please provide steps!

**Comment by jpailthorpe** [comment]
I was seeing this happen myself when a player is "read" as in game, but isn't actually in the game anymore, or is in the process of rejoining. Would like to verify if when this happens, all player's hashtags are actually in the game.

**Comment by mattwbenson** [comment]
I've managed to reproduce this once today--re-doing my steps hasn't been able to cause it again. Similar to what Jordan said, it occurred when a player didn't display on the hub screen and yet was able to still submit/vote like usual.

**Comment by johnnycrich** [comment]
Player was able to "join" game more than one on mobile until commit 396bff74782ccbc3583daba280ba2193553ddeaa. Please try to repro again.

**Comment by mattwbenson** [comment]
Unable to reproduce
