### ISSUE TITLE
HTYI: "Game is full" message not displaying in latest build

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#123]
The message that a username has already been taken isn't showing up either.

**Comment by esalling23** [comment]
does the game let more than 8 players join, or multiple usernames be the same? or is it that the error message is just missing

**Comment by mattwbenson** [comment]
Just the error messages

**Comment by esalling23** [comment]
i cannot reproduce this

**Comment by mattwbenson** [comment]
I can't reproduce it either now.
