### ISSUE TITLE
WG: after refreshing a game room, third player unable to join and game unable to start

### ISSUE THREAD

**Issue by beccachairin** [engagementgamelab/emerging-citizens#127]
After refreshing the game room and reusing the same game code to add new players, I had a few difficulties. The first was that when adding player 1 (Kylie), an error message popped up saying the game room could not be found. However, I just refreshed the player page, entered it again, and it worked. The second player (Kendall) was able to join with no hiccups. The third player (Kourtney), however, had the same error message as Kylie (could not find game room) but the error persisted even as I refreshed the join page 2-3 times.  
![screen shot 2016-08-02 at 2 41 26 pm](https://cloud.githubusercontent.com/assets/20775665/17340865/0641bc78-58c0-11e6-882f-6b3bec685036.png)

So I decided I would just close Kourtney's tab and proceed to play the game with just two players. However, when I went back to the main game page, the start button was frozen and the screen remained as is. 
![screen shot 2016-08-02 at 2 41 56 pm](https://cloud.githubusercontent.com/assets/20775665/17340908/37e9ba3c-58c0-11e6-9ea0-d1d707bf7218.png)

**Comment by beccachairin** [comment]
This happened right after the Frantz Fanon issue
#126

**Comment by jpailthorpe** [comment]
this seems to be an issue when reloading the game group screen. This is a weird edge case in the sense that once the game screen is on and going, it should not be touched (and therefore shouldn't have an issue with reloading). Not sure about technical solutions to this. My gut says that its better to immediately cancel the entire game if the group screen goes down/gets refreshed, at least right now or in the short term while we figure out a longer term fix (which will most likely need more UX and UI work). Open to suggestions though @johnnycrich

**Comment by johnnycrich** [comment]
As referenced in #139, all players are now forcibly removed from the game socket when the group view is refreshed or closed, and so this issue will likely no longer occur. Closing.
