### ISSUE TITLE
WG: iPad not autocompleting when choosing starting article

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#129]
My android tablet still offers the dropdown of possible article titles.

**Comment by jpailthorpe** [comment]
@johnnycrich maybe investigate and if code looks good, add back to the QA pipeline with reproduce me tag

**Comment by johnnycrich** [comment]
Unable to reproduce on lab locker's iPad no. 32 in both Chrome and Safari.

**Comment by mattwbenson** [comment]
Reproduced 9/9 AM build--started game with just an iPad and an android tablet, autocomplete failed to load at beginning of first round.

**Comment by johnnycrich** [comment]
This should be resolved, please try to repro again and confirm.

**Comment by mattwbenson** [comment]
Unable to reproduce
