### ISSUE TITLE
No character limit on hashtag submissions

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#13]
Players can enter hashtags that are too long and break the formatting of the page.

**Comment by jpailthorpe** [comment]
Communication specialists advocate for hashtags to be under 11 characters. Let's set a limit of 11-16 and see if that works. Might need to lower the font size to accommodate box.

**Comment by jpailthorpe** [comment]
Also will be good to see all our "real" hashtag examples and see what the upper limit tends to be. Might be more. Need to make sure real hashtags character limits are followed. Might be a good step to start there

**Comment by jpailthorpe** [comment]
see #50
