### ISSUE TITLE
HTYI: iPad page zooms in whenever loading/refreshing page

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#133]
When first joining the game, the formatting is correct. After entering a name and room code and hitting submit, the screen zooms in so that the text-entry field fills the entire page. It's impossible to zoom back out. Refreshing the page won't zoom it out either, but makes the background appear to continue to zoom in over and over.

**Comment by mattwbenson** [comment]
Once the session has been disconnected, it is possible to zoom back out again.

**Comment by mattwbenson** [comment]
Started a new lobby, page only zooms in on refreshes.

**Comment by jpailthorpe** [comment]
This is ipad specific and ONLY for HTYI? or is this a global issue?

**Comment by johnnycrich** [comment]
My guess is this is a global issue. I am looking into it.

**Comment by johnnycrich** [comment]
I've not been able to reproduce under a few tests on locker iPad no. 26

**Comment by mattwbenson** [comment]
Unable to reproduce
