### ISSUE TITLE
WG: Broken image when host game on Firefox

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#135]
![screen shot 2016-08-09 at 1 28 51 pm](https://cloud.githubusercontent.com/assets/20562141/17527219/77d32d2c-5e38-11e6-9399-0ea7d1e59f9c.png)
![screen shot 2016-08-09 at 1 29 18 pm](https://cloud.githubusercontent.com/assets/20562141/17527222/78951bbc-5e38-11e6-8651-9836a3e7d48f.png)

**Comment by esalling23** [comment]
no image in keystone for these pages - not a bug
