### ISSUE TITLE
WG/HTYI: unable to join the room on mobile device broswer that's on incognito mode/private mode 

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#138]
Testing on iPhone 6s (9.3.2) and iPad3(9.1).

Unable to press the "play" button upon the room-entering page when the mobile browser is on incognito mode (chrome), or private mode(safari).

Yet such issue doesn't exist on desktop browser that's on incognito mode(chrome), desktop safari haven't tested

**Comment by jpailthorpe** [comment]
one of the caveats we are telling people who play is to not use incognito/private browsing modes. It will be part of our FAQ on the site.

**Comment by johnnycrich** [comment]
Player will now see "You cannot play in private/incognito browsing mode. Please try again in a non-private window or tab." if trying to play in this mode.
