### ISSUE TITLE
HTYI: Refreshing Lobby without re-joining all players still allows absent players to vote.

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#139]
Login First Load: Tablet, iPad, Mac
First submission: all players submit hashtags of their own names.
First Vote: Mac votes correctly, tablet and then iPad vote for each other.
Refresh page at start of second round.
Login second load: Tablet, iPad (NO MAC) (Do not refresh Mac's window at any point)
Second submission: players submit hashtags of their own names
During second voting round, all three voting options appear on Mac's window.

**Comment by mattwbenson** [comment]
Absent player is also able to submit a hashtag during that part of the round.

**Comment by jpailthorpe** [comment]
@mattwbenson is this refreshing the page meaning refreshing the hub screen? or refreshing the player screen?

**Comment by johnnycrich** [comment]
All players are now forcibly disconnected from the socket when the group screen is refreshed. Players who do not login again after disconnect will no longer receive game events for the next session.
