### ISSUE TITLE
WG: If more than one player selects target article as starting article, game only recognizes first player

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#140]
If more than one player selects the target article as their starting article, the game will only recognize the first player as having reached the finish. The second player will have the target article loaded for them like it was just another normal article, but re-navigating to the target article still won't register a finish.

**Comment by johnnycrich** [comment]
Player is no longer allowed to target article as starting article and receives message if they try to do so.
