### ISSUE TITLE
iPad fails to load room code/name fields without clearing cache/hard reloading

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#144]
After the iPad connects to a session, anytime it refreshes the page, a "resuming your session" message appears even if the session has ended. This makes it impossible for the iPad to join a game without clearing the cache first.

**Comment by johnnycrich** [comment]
QA was missing a new template. Please try to repro again.

**Comment by mattwbenson** [comment]
I'm still getting this issue on the iPhone 4 and can reliably reproduce--I start a game with two players, one of which is the iphone, and then put both devices down to let the screens time out. Once both screens go dark and the players disconnect, the game ends. If the hub screen is then refreshed, creating a lobby with the old room code, the iPhone will read the "trying to reconnect to session" message.

**Comment by mattwbenson** [comment]
The above occurs with an iPad as well as long as the iPad is set to automatically screen-off after a certain amount of time

**Comment by johnnycrich** [comment]
Just to provide context, when the player is disconnected like this, I now clear their local session and so this does not occur.
