### ISSUE TITLE
WWDMM: mobile devices display optimization 

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#146]
devices info:

 iPod Touch 5thGen/ iOS9.3.2/ safari 

------------------------------------------

![img_0005](https://cloud.githubusercontent.com/assets/20562141/18525726/b5304cd0-7a8b-11e6-82ee-0e44dc89b62a.PNG)

**Comment by johnnycrich** [comment]
Fixed as results of meme generator refactor.

**Comment by jpailthorpe** [comment]
please verify that new meme maker
