### ISSUE TITLE
HTYI: Voting options are clipped if the viewport is wider than ~1600px 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#147]
In a full 8-player game of #HTYI, voting options become hidden once the screen gets too wide. It feels counterintuitive that having a larger screen displays less content. 
![screen shot 2016-09-14 at 3 04 28 pm](https://cloud.githubusercontent.com/assets/12397944/18526127/5a51431c-7a8d-11e6-971f-96ca9d46e64e.png)

**Comment by johnnycrich** [comment]
@esalling23 Did you fix this?
