### ISSUE TITLE
WWDMM: player pages freeze on resuming your session after refresh

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#148]
devices info:

 iPod Touch 5thGen/ iOS9.3.2/ safari 

 Droid Bionic/ android4.0.4/ built-in browser

 iPad 1stGen/ iOS5.1.1/ safari

------------------------------------------
After refreshing the host page, which naturally end the game session, player refreshing their individual game page and " resuming your session..." box jumps out and nothings happen ever since, refreshing won't clean up the "resuming" box. player need to close current page and open a new tag to see the "entering room code" tab

![img_0006](https://cloud.githubusercontent.com/assets/20562141/18526508/d61658a6-7a8e-11e6-8c0c-426c438f11d4.PNG)
![screenshot_2016-09-14-15-18-58](https://cloud.githubusercontent.com/assets/20562141/18526513/d9b77c9c-7a8e-11e6-96d3-5696165fcad6.png)

**Comment by jpailthorpe** [comment]
after you refreshed the group screen and were brought back to a room code, the phone would still try to connect to that session and would not display the game disconnected message? Or do you mean after you refreshed the phone screen it went to this resuming screen and wouldn't get out? Did the game disconnected message ever appear

**Comment by jpailthorpe** [comment]
@johnnycrich lots of issues seem to be popping up around either refreshing the group screen or trying to play again with the same room code after the game ends. Maybe we should try just reloading an entirely different room code when the game is over and brings you back to lobby, as well as when the game refreshes. This way, the device won't try to reconnect to the same room code game which no longer exists. 

...unless this is just a WWDMM thing that hasn't been updated with the newer stability/refresh code

**Comment by ritsukaBin** [comment]
After refreshed the phone screen wouldn't get out. I think game disconnected info did appear before I refreshed, need to reproduce to check

**Comment by johnnycrich** [comment]
I have resolved a number of issues surrounding these symptoms to good effect recently. I am fairly sure this was related to those, and so closing for now.
