### ISSUE TITLE
HTYI: Player image breaks if player leaves and re-joins

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#149]
I've been able to reproduce this consistently:

1. Create game with 8 players -- iPad, Samsung Tablet, and 6 chrome tabs open on a Mac.
2. Join all players to game.
3. Close one of the chrome player-tabs.
4. Re-open the tab and re-join the session.
5. Start the game.
6. The player's image will appear during submission/voting, but during round results, it breaks: 
![screen shot 2016-09-14 at 3 34 58 pm](https://cloud.githubusercontent.com/assets/12397944/18527752/16de5e74-7a94-11e6-95b6-225ac69e6833.png)

**Comment by jpailthorpe** [comment]
@esalling23 @johnnycrich Last update was Johnny assigning this to erica 12 days ago. did anyone tackle it?
