### ISSUE TITLE
Real hashtags have capital letters which signals they are real. Need to make all entries lowercase

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#15]
When you vote on the real hashtag, the real ones are displayed with their capital letters ie. BlackLivesMatter as opposed to blacklivesmatter. For ease of use, simply make all entries lowercase (user submitted) and real hashtags (I can edit this database if its easier, if not, just make them lowercase). 

This is common practice in jackbox games so should work properly.

**Comment by johnnycrich** [comment]
I may have fixed this already. Please verify @esalling23
