### ISSUE TITLE
WWDMM: Game host frozen when entering into the third round

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#153]
devices info:

 iPod Touch 5thGen/ iOS9.3.2/ safari 

 Droid Bionic/ android4.0.4/ built-in browser

 iPad 1stGen/ iOS5.1.1/ safari

------------------------------------------
in the end of second round counting down to the third, the game frozen when count to zero 

<img width="1265" alt="screen shot 2016-09-14 at 5 59 32 pm" src="https://cloud.githubusercontent.com/assets/20562141/18531610/22510084-7aa5-11e6-9dc4-6bf877484bae.png">

**Comment by johnnycrich** [comment]
Game no longer uses round countdown. Closing.
