### ISSUE TITLE
Wikigeeks: Wikigeeks stuck in infinite loop, timer keeps reseting itself when reaching 15 second mark

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#154]
Not sure how this happened. I did start the session after waiting in the lobby with three players for a significantly long time to see if I could get kicked out. My ihpone6s went to sleep, and upon waking, was still on the "waiting for players" screen. When I started the game, all seemed normal except all sorts of issues started happening, including this looping

I am assuming the game was somehow readinging as disconnected, but still let me move forward since we were "still in it"

**Comment by jpailthorpe** [comment]
qa team please try and reproduce

**Comment by mattwbenson** [comment]
unable to reproduce
