### ISSUE TITLE
wikigeeks: significant delay between clicking link in article and wiki page loading

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#155]
this seems to happen on both desktop and mobile devices. possibly due to our system trying to reformat the wikipages into our formatting? We definitely need to speed this up. In a race game, this is grueling! I would prefer to have less content or clipped content (no tables, images, etc.) than to have a delay on pages. 

Let me know what you can do to speed this up. at the least we should give players an indication that their has been registered (the red bar with the page title loaded isn't enough). Still, cutting content we display on the page is ideal.

**Comment by johnnycrich** [comment]
This is more of an issue with how after each click, we have to wait for Wikipedia to return to us the data for the next article. This is not instantaneous and is also a factor of network conditions, device speed, etc. I am not convinced that reducing the amount of HTML

**Comment by johnnycrich** [comment]
@esalling23 we should start by adding loading indicator modal that shows right when players taps link

**Comment by esalling23** [comment]
@jpailthorpe Modal has been added, will be in the next build for testing this issue!!

**Comment by jpailthorpe** [comment]
@ritsukaBin check this feature by playing with different devices, trying to break it so we can reveal any bugs.

**Comment by ritsukaBin** [comment]
ok, I will check all the assigned issue this Wednesday when I come in
