### ISSUE TITLE
Unable to Log In to qa.ecplay.org

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/emerging-citizens#156]
1. Set up a game of Wiki Geeks on Laptop.
2. Use phone browser to navigate to qa.ecplay.org.

The screen does not allow the player the option to join the game. All the player can see is the background of the login page. 

Phone = iphone 6s 
iOS = 9.3.5
Browser = Safari

**Comment by jpailthorpe** [comment]
haven;t seen this in a long time since all the updates over the last few weeks. closing for now.
