### ISSUE TITLE
keystone: Content categories are not allowed to be cross listed across games in the UI of keystone

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#157]
Johnny mentioned that categories are able to be assigned across games, but in keystone you can only select one from a dropdown. It is apparently a bug in keystone, and would need to be investigated.

**Comment by esalling23** [comment]
keystone has been updated so that lesson plans hold both a category and a gameType, but categories are no longer associated with specific games outside of a lesson plan context - closing
