### ISSUE TITLE
WWDMM: Scrolling is awkward on phones during meme creation

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#161]
The meme-creation page on mobile devices is formatted such that to reach the submit button, the user needs to scroll to the bottom of the page. However, if the first finger-press is on the actual meme image itself, the page will not scroll. Given the size of the image on the page, this can make it difficult to actually scroll at all.

**Comment by johnnycrich** [comment]
As we have no mockup for this interface, the UI is going to change. Putting this in icebox.

**Comment by johnnycrich** [comment]
Users can now scroll while touching the meme image. Still need improved layout mockup.

**Comment by mattwbenson** [comment]
Issue still occurring on voting screen.
