### ISSUE TITLE
WWDMM: Need to account for image backgrounds for displaying text

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#162]
Because we're using the white Impact font, we're going to have to be more careful about loading images that use white backgrounds or .pngs with blank alpha value
![screen shot 2016-09-28 at 3 05 18 pm](https://cloud.githubusercontent.com/assets/12397944/18929218/a031aac0-8591-11e6-9f76-af1f0360ce7e.png)

**Comment by johnnycrich** [comment]
Added black stroke to meme text for this screen.
