### ISSUE TITLE
WG: If player-window doesn't have focus until after Starting Article submission, it freezes before a random article generates

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#164]
Made a WG game with two players, but I left one of the sessions in a separate tab that I didn't re-open once I'd set it up.

Start game, continue to leave player-session minimized while using the other device.

Once the Starting Article selection finishes, and a random article has loaded on the one device, open the other session.

It stays on the form for Starting Article submission, but the game never actually disconnects until one of the player-sessions closes its window. If the main timer runs out, it will eventually display this screen: 
![screen shot 2016-09-28 at 5 31 50 pm](https://cloud.githubusercontent.com/assets/12397944/18933265/ecc4fb70-85a1-11e6-98d7-81b9754fcf81.png)

**Comment by jpailthorpe** [comment]
I think this is related to #179

**Comment by jpailthorpe** [comment]
Just checked and bug not appearing.  This is resolved since latest stability updates
