### ISSUE TITLE
WWDMM: After submitting a meme, when a player window hits back on their browser and then forward (or refresh) after bringing them back to the session the game lets them make another meme and submit it. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#167]
two players in game. 

1. player 1 create meme + submit. get "wait for others to submit" screen message on device. player 2 does nothing. 
2. player 1 hit back button 
3. player 1 hit forward button 
4. player 1 screen auto refreshes and takes back to session, but instead of "wait for others to submit" it thinks player 1 didn't submit a meme yet and asks player 1 to create one. The player tab name is no longer listed as "EC:playername" and instead just says "emerging citizens" 
5. When submitting new meme, the game thinks I am the other player (who didn't submit a meme yet) and then takes us right to the voting screen.
6. the voting screen on one player 1 device shows the second meme player 1 created. The voting screen on player 2 screen shows an auto-generated meme (thinking the player 2 didn't submit a meme in time).

**Comment by jpailthorpe** [comment]
@johnnycrich not sure if this is covered in trello, but will add to checklist

**Comment by jpailthorpe** [comment]
update on this: The game lets player 2 vote on both the auto generated meme AND the original meme submmited.

**Comment by johnnycrich** [comment]
Fixed.
