### ISSUE TITLE
WWDMM: Devices cropping/stretching memes strangely during initial image selection

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#168]
Once the meme is submitted, the meme appears correctly formatted, but before that point, it appears cut-off on the device
![img_0009](https://cloud.githubusercontent.com/assets/12397944/19127081/8536f25a-8b0b-11e6-8e2a-43b2921ee7b9.PNG)

**Comment by jpailthorpe** [comment]
Checked this on iphone5s + ipod. Fixed since issue created. Closing!
