### ISSUE TITLE
Global: iPad console returns error "Failed to load resource"/server 422 on trying to load Smartlook

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#172]
![screen shot 2016-10-26 at 2 30 37 pm](https://cloud.githubusercontent.com/assets/12397944/19739560/6760b372-9b89-11e6-842e-01bed59983f7.png)

**Comment by jpailthorpe** [comment]
Smartlook is the video tracking system I have that records every session of play. As long as this is not interfering with gameplay / doesn't affect front end it's not a big deal.

**Comment by jpailthorpe** [comment]
We decided to just remove smartlook from production. I will try to find a new solution to track user engagement, but for now, smartlook is out. closing
