### ISSUE TITLE
WG: iPad can't scroll down articles

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#175]
When the iPad loads an article, only the content that first appears in the viewport is readable. The window behaves like there is no more content "below the fold" and prevents scrolling. This effectively cuts off articles below their intro blurb and makes playing nearly impossible.

**Comment by jpailthorpe** [comment]
Does this only happen on iPads?

**Comment by mattwbenson** [comment]
Yeah, only iPads, not iPhone/iPod.

**Comment by mattwbenson** [comment]
Occurs on both Chrome and Safari.
