### ISSUE TITLE
WikiGeeks: Game lost track of where players were after first round, and after players submitted starting articles fo the topic in round 2, the next main screen went to the same topic screen in round 1. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#179]
devices: iphone6plus(Jordan-chrome), iphone6(Erica-chrome), iphone5s(wade-safari), iphone 6(christina-chrome) 
1. We played round 1(topic Sept 11), and christina got to the target article almost at the very last second. 
2. Results screen + leaderboard was correctly displayed, no issues. clicked on to next round. 
3. Given round 2 topic (blues). all submitted starting articles except wade who guessed the correct article. Yet as he got that message, the game took other players phones to our starting articles, though Erica was sent to the starting article she selected from round 1, Jordan was sent to the correct article, and christina was sent to a different article she typed in and never saw (but I think this was a redirect since it was still music related). 
4. Main screen at the ame time transistioned to the SAME topic screen from round 1 (sept 11 attacks). Wade's phone never went anywhere. We also never got a modal, though I think we might have been out of time? 

At this point we stopped playing.

**Comment by johnnycrich** [comment]
I have a fix for the issue Erica experienced but not yet for the round topic using the prior topic.

**Comment by jpailthorpe** [comment]
This happened again with eight players across multiple devices and broke the game. this happened while people were searching for the revealed article. The topic was zika virus and the revealed article was american heart association. 

Interestingly, I ONLY selected "US Politics" category, and I know for a fact that zika virus is not a part of Us politics, so there seems to be a bit more.

**Comment by jpailthorpe** [comment]
also related to #189 and #211
