### ISSUE TITLE
When trying to join a game from mobile, html buttons do not function and can't join game.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#18]
On Iphone5s and iphone6. Tried in google chrome(50.0.2661.95) and Safari (?). 

buttons just aren't responsive. Maybe the template is off, due to same problem on both phones and browsers

**Comment by jpailthorpe** [comment]
also the buttons looks different on mobile: 
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/10051544/15191160/66526b88-1781-11e6-9ca9-d82896a85f21.png)

**Comment by johnnycrich** [comment]
Working fine for @esalling23 on iphone.

**Comment by esalling23** [comment]
@jpailthorpe do you mean the input fields or the "play" and "help" buttons?

**Comment by jpailthorpe** [comment]
play and help buttons. I can input name and room code

**Comment by jpailthorpe** [comment]
I tried again and still cant seem to get the buttons to work. Will show tomorrow.

**Comment by jpailthorpe** [comment]
This has never worked on my phone, and Erica was getting the same problem with her 5c.

**Comment by jpailthorpe** [comment]
This has something to do with devices using field inputs. I came across this same exact problem one a different website very recently (I think it was the somerville parking authority site).

**Comment by jpailthorpe** [comment]
fixed
