### ISSUE TITLE
GLOBAL: When players submit across all games, portraits + names do not reflect specific players. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#184]
For example, I submitted my hashtag. upon submission, the portrait for Sam lit up. Then, when Sam submitted her hashtag, the portrait and name for Jordan lit up.

**Comment by mattwbenson** [comment]
I'm still seeing this issue--it also looks like icons are appearing for players who were never in the game. So, for example, player "Matt" starts a 4-player game with the player4 icon, but then immediately in the first round, "Matt" has the icon for player6. As the game continues, other players will be assigned icons for players 5-8.

**Comment by jpailthorpe** [comment]
reproduce by following these steps:

start a game with more than three players
in the first section in the "Create" phase, refresh one player's screen.
upon return and after submitting content for that player, that player's portrait doesn't light up, and instead that submission is reflected in a random player's portrait.
should note that this does not change what content is is associated with which players (ie. my meme I submit is still attached to my name and I still get points for votes). So this is simply a cosmetic thing, but really confuses players from a ux perspective.

**Comment by mattwbenson** [comment]
I didn't have to go through those steps to see this happen on my playthrough of HTYI. I just started a 4 player game, and on the first screen the icons were immediately different from the ones in the lobby.

**Comment by jpailthorpe** [comment]
Erica might have fixed this @johnnycrich so might be best to check on QA before spending time investigating.

**Comment by mattwbenson** [comment]
Still having this same issue with HTYI--Playing with four players (samsung phone, samsung tab, iPad, and iPhone 5), after the game starts, the players immediately lose their icons and have them replaced by ones that were never active in the game.

**Comment by jpailthorpe** [comment]
but do the portraits + names swap themselves? So for example, jordan has icon 1 and matt has icon 2, at any point does my action of submission highlight anything except my portrait? I am okay if the portrait "face" changes. that is a sep. issue

**Comment by mattwbenson** [comment]
It's hard to tell as is, because players 4 and 5 currently have the same asset for their icon.

**Comment by jpailthorpe** [comment]
gotcha. That seems like a sep. issue we should log in new. I just want to make sure that when a player is in a game, refreshes and then submits, the main screen doesn't show another player's portrait and name light up while theirs remains dark.

**Comment by mattwbenson** [comment]
Okay, cool. In that case, yeah, I'll make new issues for those
