### ISSUE TITLE
Wikigeeks: Some wikilinks in keystone have spaces after their title names, causing link breakage/freezing game 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#188]
an example of this is the "Inconvenient Truth" category. There is a space after the title, which breaks the game because it is impossible to to find the exact article. 

This should be fixed by content team members. Please focus first on the US politics category.

**Comment by mattwbenson** [comment]
Just checked the list--only found one case of this, for "The Race Question"
