### ISSUE TITLE
WikiGeeks: When a user tries to refresh their game when the game state has already changed, the game freezes out that player. That causes the game to not advance after article is found. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#190]
1. Was navigating through articles. Pressed back on browser.
2. Refreshed. worked just fine
3. hit back. stayed on that screen
4. game timer ran out and said two other player windows worked properly, giving warning. 
5. when refresh of player window that was still out of game (aka. didn't refresh before the state change) the game brought to "resuming your session" screen, but never advanced past that. Game didn't know where to bring the player.
6. Once another working player found the article (national voter reg act), their player windows showed the path taken and transistioned properly, but main screen stayed on find the article screen. It did indicate proper player who won, but would not move from that screen. 
7. upon refresh of two player windows that were working, they were taken to "find your starting article" screen. I could select an article and lock in, but the game never advanced after that. 

here is a video for the experience. the video picks up right after number 4 

[https://drive.google.com/open?id=0B2iJJeD7RJtgdWFIYTlmelUxNUE](url)

**Comment by jpailthorpe** [comment]
@johnnycrich is the fix for this the idea that they enter back in at a different point in the round ?

**Comment by mattwbenson** [comment]
Just had this happen inadvertently on the old Samsung phone. I had set up the starting articles on the other two devices, but when I went to submit it on the phone, Chrome crashed on the device. When I restarted it/refreshed the page, the player wasn't allowed to rejoin and the game moved on without it.

**Comment by mattwbenson** [comment]
Unable to reproduce, any time I recreate steps, I just cause issue #214.

**Comment by jpailthorpe** [comment]
I am going to move this back into the backlog, since I think this is also related to all these WG stability issues, and will help johnny better see the breadth of the issue.

**Comment by mattwbenson** [comment]
Currently unable to reproduce--at least in the current build, playing around with "Back" and "Reload" to trigger the issue only causes the player to be booted for "inactivity".

**Comment by jpailthorpe** [comment]
How often do they get booted and how fast do they get booted? immediately after hitting back? after a bunch of times? etc.

**Comment by mattwbenson** [comment]
It's not immediate--I have to cycle back and forth between back and reload a couple of times. I watched your video, and tried to reproduce your clicks, play with clicking through links and reloading, etc, but I can't get it to happen.

**Comment by jpailthorpe** [comment]
okay great. Good enough for me to be considered enough of an edge case that won't break core normal use. Considering this main issue to be done.
