### ISSUE TITLE
HTYI: Menu on game group screen not functioning. When trying to click, nothing happens. Seem like the menu is not integrated into HTYI even though it is in other games

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#195]
This was tested to be true on chrome + Macbookpro + Macbookair. This is only happening in HTYI and not across all games. 

<img width="968" alt="screen_shot_2016-10-19_at_7 10 40_pm" src="https://cloud.githubusercontent.com/assets/10051544/19862201/c1110fea-9f65-11e6-98f9-0400f1e61958.png">

**Comment by johnnycrich** [comment]
Does not occur for me on Macbook Chrome for this HTYI game: https://emergingcitizens.org/game/BXRN

**Comment by jpailthorpe** [comment]
hmm... guess it is working now for me too.

**Comment by jpailthorpe** [comment]
closing for now
