### ISSUE TITLE
Global: Times almost up message appears too quickly (at halfway point of timer) and should only appear at around the 15 second mark. Change copy across games to say "You have 15 more seconds! time is almost up!" to give better direction to players.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#197]
This was tested and validated through playtest sessions where users would get flustered for time being almost up when they would actually sometimes have a full 30 -60 seconds left. Giving clear indication of how much time they have left + only showing that when its actually very close to time being almost up (jackbox does it at ten seconds) will give us a better user experience. 

Change copy across games to say 

"You have 15 seconds! Submit your answer!" to give better direction to players.

**Comment by mattwbenson** [comment]
Occurring, noticed during Wade's playtesting group 11/4
