### ISSUE TITLE
Global-QA: Test games on mobile screens using the iphone5s and iphone4 for any formatting problems. We have here to make sure all inputs are functioning and screen is not cutting off. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#206]
We had some issues playing WWDMM and wikigeeks on iphone5s. The elements were cutting off input boxes due to the screen not scaling to the small area. 

lets make sure this is being tested and then we can address concerns from there. 
Make note whether...
1. a screen state due to formatting or control is completely unplayable. 
2.  if its inconvenient (but still playable)
3. or if something aesthetically looks bad but still works and is easily understood how to get it to work. This will help us prioritize. every instance should be outlined as a new issue in git under new.

**Comment by mattwbenson** [comment]
HTYI: iPad has the "waiting for next round" text floating to the top of the cloud, while on iPod/iPhone the text is completely breaking out of the cloud.
