### ISSUE TITLE
Wikigeeks: on mobile screens, the red box is being reduced to 1px and displays as straight line. Text is centered

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#207]
This is just a cosmetic issue and doesn't affect gameplay. 

![slack for ios upload-1](https://cloud.githubusercontent.com/assets/10051544/19907222/459bface-a054-11e6-98fa-506646db6d07.jpg)

**Comment by esalling23** [comment]
Cannot reproduce - may have been already fixed

**Comment by mattwbenson** [comment]
Can't reproduce on any of the lab iOS/Android mobile devices
