### ISSUE TITLE
WWDMM: player created names are being cutoff in voting screen

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#208]
someone typed their name as Ronald Reagan. The game displayed this name fine except when it was recorded as a vote. I think this has to do with the way it breaks the line. We should simply limit the name on the login screen to a set amount of characters

**Comment by jpailthorpe** [comment]
To be more clear, what I am referring here is on the vote round results screen when the score is displayed. due to the line break, it pushes the score down and overlaps onto the other name.

**Comment by esalling23** [comment]
I limited the player names to be 15 characters, and increased the height of the votes so that they do not overlap, even if someone's name is Ronald Reagan!
