### ISSUE TITLE
HTYI: some tweets in the system are getting [...] due to character length. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#209]
For example, #makeamericagreatagain is the REAL hashtag, and due to its length, it gets the elipsis treatment. I'm fine with this happening when it is a user generated hashtag, but if the real hashtag gets cut off players think its not real.

**Comment by esalling23** [comment]
@jpailthorpe This might also be a reveal for players who have seen the screen for a while, and notice that some are cut off while others are not. MakeAmericaGreatAgain is 21 characters, with the limit having been set to 20 before - If I change this limit to 25 or 30 characters, that should accommodate most trending hashtags. Does that work?

**Comment by jpailthorpe** [comment]
I think extending the character limit just one more character should do the trick and less risk of any format breaking. Lets try that

**Comment by mattwbenson** [comment]
This issue is 'resolved,' but you can still identify player-created tags by their ellipses.
