### ISSUE TITLE
wikigeeks: I selected us politics as a category, but it pulled in a topic for health. checked in keystone and it is not connnected

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#211]
1. selected content category us politics
2. content topic loaded was from the health category
3. strange round refresh problem occured. 

I have NOT seen this happen in anything except for wikigeeks, but that doesn't mean its not happening. just never replicated in other games. 

Not sure if related to #179 and #189

**Comment by johnnycrich** [comment]
Thus far I have not been able to reproduce. Assigning to @mattwbenson to try.

**Comment by mattwbenson** [comment]
I remember this happening while I playtested on Friday with four devices
(iPhone, iPad, ipod, and Samsung phone) , whatever that's worth. Only
selected us politics, got enzymes as a topic.

**Comment by mattwbenson** [comment]
Just reproduced with samsung tablet, iPad, samsung phone, and iPhone 5s. Selected "US Politics" as the only category, and the first topic when the game starts is "Organ Donation."

**Comment by mattwbenson** [comment]
See #227
