### ISSUE TITLE
HTYI: Formatting breaking during voting stage

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#213]
It's doing this consistently every round, currently playing with four players.
![screen shot 2016-11-04 at 10 51 42 am](https://cloud.githubusercontent.com/assets/12397944/20010099/48d5ba56-a27d-11e6-9ea0-afa667a7797f.png)

**Comment by jpailthorpe** [comment]
@esalling23 make sure to check up on this, as i assume this is happening due to some other issues you are working through

**Comment by esalling23** [comment]
@jpailthorpe have a fix for the voting group screen, working on results screen now!

**Comment by jpailthorpe** [comment]
checked
