### ISSUE TITLE
Wikigeeks: Round starts over from article-selection in the middle of the round

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#214]
Was trying to reproduce #190 in a 4-player game. Clicked "back" and then "forward", doing a cycle a couple of times until refreshing caused the iPad to get kicked from the game for "inactivity."

 After starting to do the same on the iPhone 4, ALL devices switched to starting article selection momentarily, before going back to their respective articles. 

Refreshing it one more time caused the hub screen to move to "choose a starting article about" screen, and ALL devices moved to starting article submission, even those that hadn't been back-forward-refreshed.

**Comment by jpailthorpe** [comment]
@mattwbenson when the game refreshed the main screen, at what state was the players in? Did the game already move into the "find the revealed article" ? or was this during the first two minutes? 

#179 #189 #190

**Comment by mattwbenson** [comment]
The game was in the "find the revealed article" state
