### ISSUE TITLE
HTYI: iPad is cutting off top of all screens

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#224]
![img_0047](https://cloud.githubusercontent.com/assets/12397944/20279753/c682269a-aa77-11e6-9add-d67a5eb72185.PNG)

This behavior continues through each section of each round, with the same amount cut off the top on all screens.

**Comment by jpailthorpe** [comment]
only ipad?

**Comment by mattwbenson** [comment]
Yep.
