### ISSUE TITLE
WG: Game produces irrelevant link for category, if link topic is shared across categories

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#227]
Kind of related to #211--might even be the same issue--where the game is loading content that doesn't match the category selected, but this seems more a design issue than a technical one. I selected "US Politics" alone as a category, and received "Health Care" as a starting topic. "Health Care" is a topic for both US Politics and Health. After I chose my starting article, I was given the target article of "Neurobiological Effects of Physical Exercise", which is a link in the "Health Care" topic--but really only works for "Health" as a category, and not "US Politics". This is "correct" for the system and how it's designed to run, but makes really no sense from a gameplay/UX perspective. 

A quick temporary fix would be to allow each topic to have only one category, but this is a larger information architecture issue.

**Comment by jpailthorpe** [comment]
gotcha! Lets make it so each topic is only tied to one category. This content is only being used for demoing purposes and therefore any content that hinders understanding of how the platform works goes against this main goal. Therefore, feel free to make changes to the content in any way you deem best. Would like Sarah and you to focus on this tomorrow with the goal of clearing one category at a time.

**Comment by jpailthorpe** [comment]
also do this on production NOT QA!

**Comment by mattwbenson** [comment]
On QA keystone, each topic now only has a single category assigned to it, so this issue should be "fixed". Whenever the back-end tweak gets pushed to production, somebody will have to re-link the topics to categories there as well.
