### ISSUE TITLE
Global: Game allows players with identical names

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#228]
Based on description of #199 , I tried to see if I could get two players with identical names into one lobby. Using the same technique--hitting "play" on both devices simultaneously--worked, and got both players in with the same name. The game still assigns each player their own icon and tracks their score separately. The only 'bug' this caused was preventing the background texture from loading on one of the devices--the iPod Touch--but it only did this once, and the texture successfully loaded the next time I reproduced this issue. 

Not clear if this causes any other problems, but creating issue to document.

**Comment by jpailthorpe** [comment]
I think the texture issue is not related to the naming quirk and is instead related to content loading on slower devices/connections. A refresh usually fixes that problem, but is also documented in another issue. 

As long as having the same name doesn't break anything on the gameplay/system side, I am okay with this. Nice thinking/testing though!! A+
