### ISSUE TITLE
when using iphone5s in landscape mode, player view screen hides user input fields 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#23]
When I try to use my phone in landscape mode, the header and footer covers the input fields on the room code entry screen. 
![slack for ios upload 2](https://cloud.githubusercontent.com/assets/10051544/15199041/64e2efb6-17a9-11e6-8f6c-ec7996ccf9e1.jpg)

**Comment by johnnycrich** [comment]
Header is now hidden for mobile.
