### ISSUE TITLE
Major Connectivity Issues: EC Global (Loads, device connections)

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#248]
Currently, the production server is loading content noticeably slowly, especially when compared to QA. It can take over a minute to load category selection, and as long/longer to actually load the game lobby. Once the lobby has been loaded, it is impossible to join--any time the room code is entered into a device, the device returns the error that the room code does not exist. This is the case for all three games, and when trying different categories/combinations.

**Comment by johnnycrich** [comment]
Resolved via 3b1eec73ee6ba314f02074308ed2994af7f5c8ca

**Comment by mattwbenson** [comment]
After 3b1eec7, content loading issue is fixed, but devices still get error codes/rejected from game lobbies.

**Comment by johnnycrich** [comment]
Ok, you should be able login now via fix in 796fdba243e1661ca742789471cca42ca41086de
