### ISSUE TITLE
Multiple players entering the same hashtag breaks voting

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#36]
The voting option appears on all players' screens but one, and voting for anything on any screen breaks voting.

**Comment by mattwbenson** [comment]
Play continues after question timer times out, but the one player who was able to vote is removed from the game lobby. Their screen remains unchanged, though, and just says "submission received."

**Comment by johnnycrich** [comment]
I am going to resolve this issue right now by not enforcing that hashtag submissions be displayed as unique per player, but this brings up a UX issues (i.e. player 1 might see player 2's hashtag on their voting screen, even if its identical to their own).
