### ISSUE TITLE
UX:Common hashtag abbreviations still clear the check for players submitting the real hashtag

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#38]
I.E. #BLM can be submitted for #blacklivesmatter or #GG/#StopGG for gamergate.

**Comment by jpailthorpe** [comment]
do you mean you can enter blm for blacklivesmatter and it will say its correct?

**Comment by jpailthorpe** [comment]
Or are you suggesting we should ALLOW this to be correct? I don't think its a good idea to approve variations of a hashtag in that creation process, because just like in fibbage, it only works if it is EXACTLY the same.

**Comment by mattwbenson** [comment]
No, I mean the game prevents you from submitting #blacklivesmatter but not #BLM, which makes voting for the "real" hashtag kind of pointless.

**Comment by mattwbenson** [comment]
Because instead of guessing what the real hashtag is, I'm guessing what the proper formatting is?

**Comment by mattwbenson** [comment]
We'll leave this to playtest out
