### ISSUE TITLE
Winners' Circle/Leaderboard displays order players joined game, not top scorers

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#39]
Creating games where the top scorers are the last players to join the game, the winners' circle doesn't display them at all, and they're listed last on the leaderboard.

**Comment by jpailthorpe** [comment]
This sounds like a game breaking bug in terms of gameplay. Basically does mean that players who have the highest score aren't being projected as having the highest score?

**Comment by mattwbenson** [comment]
Correct

**Comment by johnnycrich** [comment]
I believe I fixed this a while ago since I cannot repro.
