### ISSUE TITLE
Playing a game on multiple devices: Hashtag submission doesn't end automatically after all players submit

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#40]
It looks like there are extra players in the lobby somehow, even though none joined.

**Comment by mattwbenson** [comment]
This is now happening during voting too.

**Comment by mattwbenson** [comment]
Seems linked to issue #41 , I only get this behavior if I stop actively keeping the tablet screen awake and the tablet times out of the session.

**Comment by johnnycrich** [comment]
If a player is disconnected, the player count now decreases properly. This may alleviate this issue. Please confirm.

**Comment by jpailthorpe** [comment]
If this basically means that when the player's screen goes to sleep, they get kicked, but the rest of the sesion continues as normal, I am okay with this for ths time being Obv. its not perfect, but there are bigger fish to fry. 

Might be good to see what kinds of devices this happens on (does this ONLY happen on android tablets? ios? etc.) and then including these devices in a list of non-fully supported devices? this way we can try to mitigate this happening

**Comment by jpailthorpe** [comment]
Lets test this again to make sure its true
