### ISSUE TITLE
On Android Tablet, if screen powers off between rounds, it gets disconnected from session

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#41]
It's stuck at the end of round screen and won't move on to the next round.

**Comment by johnnycrich** [comment]
Fixing this required a fun hack: I make the browser think there's a video playing. 💯

**Comment by mattwbenson** [comment]
After a brief delay, the tablet is eventually able to submit/vote, but when the next leaderboard appears, that player has been dropped from the game.

**Comment by mattwbenson** [comment]
Tablet isn't able to submit after that point, but can still vote.

**Comment by johnnycrich** [comment]
I've yet to be able to get a device to disconnect via going to sleep.

**Comment by jpailthorpe** [comment]
Is this fixed?

**Comment by johnnycrich** [comment]
I cannot reproduce it.

**Comment by jpailthorpe** [comment]
just like 72, I think these are ancient problems that we already fixed, but just to be sure, please check. If we aren't sure, lets move these to QA pipeline to try and reproduce

**Comment by johnnycrich** [comment]
Should be fixed as of commit 2953101a8264b523298f7dd2afe3828c21fb6ad6. Please confirm.

**Comment by mattwbenson** [comment]
Unable to reproduce
