### ISSUE TITLE
Grey color for voting options appears transparent on Apple Devices

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#43]

**Comment by jpailthorpe** [comment]
I don't understand this. Can you elaborate?

**Comment by mattwbenson** [comment]
One of the background colors for the voting options is grey on all devices,
except ios, where it appears transparent.
On May 23, 2016 12:38 PM, "Jordan Pailthorpe" <notifications@github.com>
wrote:

I don't understand this. Can you elaborate?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/engagementgamelab/emerging-citizens/issues/43#issuecomment-221026034>

**Comment by jpailthorpe** [comment]
Can we just remove this color?
