### ISSUE TITLE
When a person enters the exact same fake hashtag as another player, it should combine into one answer

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#51]
Through playtesting we found that players would sometimes enter the same FAKe hashtag and it would create duplicate answers on screen. The bigger issue here is figuring out how to display only one answer, but award equal points to both players who submitted that hashtag. We then need to show on screen in the reveal process that it was BOTH player's hashtags. 

This is an important issue to resolve.

**Comment by esalling23** [comment]
fixed with new build
