### ISSUE TITLE
Mobile/Ipad player platform formatting strangely

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#57]
The entry fields are right-aligning so that there is a margin on the left but not on the right. Ipad problems are limited to older-version iPads, newer versions are displaying properly.

**Comment by mattwbenson** [comment]
On both Android and iOS tablets, the "waiting for other players" dialogue is also uncentered from the cloud bubble and is hard to read.

**Comment by jpailthorpe** [comment]
fixed
