### ISSUE TITLE
Only three players can join a game

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#59]
Whenever more than three try to join a lobby, the third player gets kicked from the session and the fourth player takes their place.

**Comment by mattwbenson** [comment]
But all four devices get question prompts when the game starts.

**Comment by mattwbenson** [comment]
Continuing with more than three players breaks the results round.

**Comment by johnnycrich** [comment]
Unable to repro, possibly was related to #60
