### ISSUE TITLE
Longer Hashtags run past the border of their boxes

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#65]
"#GiveCaptainAmericaABoyfriend" is doing this, for example.

**Comment by jpailthorpe** [comment]
Will this be resolved now that we are scaling? @johnnycrich

**Comment by esalling23** [comment]
fixed in next build

**Comment by esalling23** [comment]
Fixed on front end UI with elipses - there is already a limit on how many characters players can enter for a hashtag, so if this is an issue with real hashtags being beyond that limit, we should discuss how exactly we want to fix this @jpailthorpe

**Comment by jpailthorpe** [comment]
I just removed that particular hashtag because it was the only one longer than 25 characters
