### ISSUE TITLE
The indicator for total points earned in a round never goes higher than 50

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#68]
The next indicator for total points in the game starts to function incorrectly after the first couple rounds.

**Comment by mattwbenson** [comment]
Points earned in previous rounds are also displaying.

**Comment by mattwbenson** [comment]
This indicator seems to break whenever all players correctly guess the hashtag.

**Comment by jpailthorpe** [comment]
This might also be connected to how Sam and I were not receiving any points when we both guessed the correct hashtags. It happened in two rounds, both of us showing 0 points, and when the reveal happened it didnt have the "this is the real hashtag" purple bar.

**Comment by esalling23** [comment]
I may have just fixed this, I have the scores totaling correctly on my local machine
