### ISSUE TITLE
Players aren't prevented from typing the real hashtag

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#7]
If a player submits the real hashtag, the submission should be rejected and the player advised to create an original hashtag.

**Comment by jpailthorpe** [comment]
Another way to do this which I'm okay with is simply giving a notice to the player that they guessed correctly by checking their submission against the real hashtag. The message also says a stock hashtag will be placed. I think the wording in the directions need to be clear to the player that they should be trying to fool other players, not guessing the real hashtag, in that first submission section. This I think is more a ux issue than a technical one
