### ISSUE TITLE
on iphone 6s plus, when my phone goes to sleep it kicks me out of the session upon return. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#72]
I end up back at the join a game room code screen.

**Comment by jpailthorpe** [comment]
This does not happen on sams phone

**Comment by jpailthorpe** [comment]
Is there a specific iphone setting that is doing this? If so, we should just note it in a faq as we go through the open beta.

**Comment by jpailthorpe** [comment]
#41 duplicate

**Comment by jpailthorpe** [comment]
this should be fixed correct @johnnycrich ? this was before our refresh system

**Comment by johnnycrich** [comment]
Should be fixed as of commit 2953101a8264b523298f7dd2afe3828c21fb6ad6. Please confirm.

**Comment by johnnycrich** [comment]
Still waiting on QA confirmation

**Comment by jpailthorpe** [comment]
Bin also check this as well. post update if can't reproduce problem and move to done

**Comment by jpailthorpe** [comment]
to clarify, if your phone goes to sleep ON ITS OWN it will kick you out. If you MANUALLY put your phone asleep, it should automatically resume if the game is still going. 

curious though @johnnycrich if there is actually a certain time limit that if it is asleep, even manually, for a certain period of time, it won't resume (like asleep asleep). Also iOS changes how the phone sleeps/wakes now. should probably verify

**Comment by ritsukaBin** [comment]
REPRODUCE:

Iphone6s safari/ipod safari/mac chrome

When ip6s went to sleep(auto lock), it got kicked out, shown as this: 
![img_7448](https://cloud.githubusercontent.com/assets/20562141/18929898/1545dfbe-8594-11e6-8a15-2b6a553a52c2.PNG)
--and after refresh, ip6s went to entering-room-code page

Yet the ipod that went to sleep at the same time didn't
![img_0008](https://cloud.githubusercontent.com/assets/20562141/18929956/2aaf51a0-8594-11e6-846c-a685d03785fd.PNG)

**Comment by ritsukaBin** [comment]
This even happens when I manually put my ip6s into sleep
