### ISSUE TITLE
winners circle doesn't display the winners in order of points, only in order of who joined first

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/emerging-citizens#76]
The winner of the game was placed in the middle of the the screen instead of on top, and the order in which they appeared was determined by who joined the game, not their point score

**Comment by jpailthorpe** [comment]
I only played this test with three players total, so I am worried that if there are more than three and the actual winner is not in the winners circle, it will be very confusing to the players

**Comment by esalling23** [comment]
Should the final scores be displayed in opposite order (3rd to 1st) or display the winner first, and then the 2nd and 3rd
