### ISSUE TITLE
If two players enter the same hashtag, both options appear on the voting screen

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#8]
If two players create the same original hashtag, it should only appear once in the voting screen, and both players earn points if somebody votes for it.

**Comment by jpailthorpe** [comment]
This I agree with. Let's replace the duplicate with a stock generated hashtag. We will need to build this database out so Johnny can have the game automatically Input another hashtag to match the number of hashtags that appear with the number of players in the game. 

It might be okay if there are fewer hashtags too. I think this is more of a game play feel than anything else.

**Comment by johnnycrich** [comment]
All I can do for now is generate a random word for dupes. Let me know if this works for now @jpailthorpe
