### ISSUE TITLE
Avatars in winners' circle are popping out of their backgrounds

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#80]

**Comment by johnnycrich** [comment]
@mattwbenson Please provide screenshot.

**Comment by mattwbenson** [comment]
![screen shot 2016-06-23 at 11 16 44 am](https://cloud.githubusercontent.com/assets/12397944/16308701/16fcdab2-3934-11e6-9932-48a33ba5ab32.png)
