### ISSUE TITLE
WG: Screens animate out way too quickly to be readable

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#89]

**Comment by johnnycrich** [comment]
@mattwbenson you mean the countdowns are too fast?

**Comment by mattwbenson** [comment]
No, well, yes, they are, but I mean, like, the scoreboards and all that appear and disappear way too quickly, especially if there are only a few clicks.

**Comment by mattwbenson** [comment]
Like, there's something going wrong with the clickmap, but it disappeared too quickly for me to figure out what it was.
