### ISSUE TITLE
WG: Unable to hit enter on mobile device (iPhone 6s)

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#90]
Setting environment: 3 player (2 from MacOS chrome, 1 from iOS safari)

The two players from desktop were able to start the game properly by entering the "start link article", while the page on the iphone froze, unable to hit enter.

![img_7256](https://cloud.githubusercontent.com/assets/20562141/17145121/0d195072-5327-11e6-8fad-6ecabf817bbd.PNG)

**Comment by johnnycrich** [comment]
Fixed as of commit 52a0120fe0a5a80d1526a842d5fce6859e45d01f.
