### ISSUE TITLE
WG: browser backward and forward control provide shortcut for cheat under certain circumstance(updated)

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/emerging-citizens#92]
Environment: 2 players(MacOS Chrome)

Step by step process as following: 

1. both player starts out the game not from a blank page but by refreshing the previous game page.
<img width="1440" alt="screen shot 2016-07-26 at 12 18 14 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146311/f5ef086a-532b-11e6-893b-347acb893c71.png">
<img width="1440" alt="screen shot 2016-07-26 at 12 18 31 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146320/fcaee4b8-532b-11e6-8642-7d9c67ecba21.png">

2. both player starts the game 
<img width="1440" alt="screen shot 2016-07-26 at 12 20 27 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146381/44b4e870-532c-11e6-84c7-bd94a82b6032.png">

3. player "d1" clicking backward then jump to this page:
<img width="1440" alt="screen shot 2016-07-26 at 12 20 35 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146432/7657ef12-532c-11e6-8b72-33373605dda1.png">

4. "d1" cheating on game
<img width="1440" alt="screen shot 2016-07-26 at 12 20 56 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146445/891b008a-532c-11e6-9db2-0e88f4aeadf4.png">
<img width="1440" alt="screen shot 2016-07-26 at 12 21 03 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146447/8d42a35c-532c-11e6-9231-39cda62b968d.png">

5. yet same glitch didn't replicate on player "d2", which start out in the same way as "d1". It follows normal "gamepage-blankpage-gamepage" process.
<img width="1440" alt="screen shot 2016-07-26 at 12 21 14 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146512/ccbb7fd6-532c-11e6-9bae-71877d143cd0.png">

Also, after both player finding the target article, the scoring page still went kind of funky.
<img width="1440" alt="screen shot 2016-07-26 at 12 22 23 pm" src="https://cloud.githubusercontent.com/assets/20562141/17146567/00e02cee-532d-11e6-98dd-ac9621c4975f.png">

**Comment by esalling23** [comment]
should be fixed by session storing current article -- also confirmation of going "back" kicks player out of game -- closing for now
