### ISSUE TITLE
WG: A device will sometimes fail to connect to the game

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#93]
While the other devices have the option to enter their starting article, lagged-out devices just read "Waiting for other players..." while the game is ongoing.

**Comment by mattwbenson** [comment]
This occurred on the old Samsung tablet from the equipment case.

**Comment by mattwbenson** [comment]
Just had this occur again with an iPad. The device joined on the hub screen, but didn't appear to on the device screen. Trying to join the lobby returned a message that the name was already used.

**Comment by jpailthorpe** [comment]
Just referenced you in the issue this one references. Erika thinks its related, which seems to be the case.

**Comment by jpailthorpe** [comment]
Need ti verify fixed with new updates

**Comment by mattwbenson** [comment]
Unable to reproduce
