### ISSUE TITLE
WG: When reloading group screen to replay a game, many things break including the following: Timer and "Out of Time" message displaying simultaneously

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/emerging-citizens#96]
![screen shot 2016-07-27 at 11 02 43 am](https://cloud.githubusercontent.com/assets/12397944/17180233/b71a23fe-53e9-11e6-8119-c1c85cc72cf8.png)

**Comment by esalling23** [comment]
please provide steps taken to reproduce

**Comment by mattwbenson** [comment]
I'm honestly not sure, it happened at the start of the game, and I don't
recall doing anything different.

**Comment by esalling23** [comment]
next time this is seen we should get steps - try logging in differently etc to see if it happens every time or if there is a specific step that is causing this

**Comment by ritsukaBin** [comment]
I got this problem reproduced. It happened when the time player enters the starter article too close to the time-countdown limit (in my tests I press enter when the countdown is 3 or 2 second). 
<img width="1440" alt="screen shot 2016-07-27 at 2 22 43 pm" src="https://cloud.githubusercontent.com/assets/20562141/17187103/e2133110-5405-11e6-88c4-fe561ea14bd3.png">
 
<img width="1440" alt="screen shot 2016-07-27 at 2 22 50 pm" src="https://cloud.githubusercontent.com/assets/20562141/17187222/5e13888c-5406-11e6-88eb-ff04ea934ed8.png">

**Comment by jpailthorpe** [comment]
Again, another issue related to re-loading the the group screen.

**Comment by johnnycrich** [comment]
I was unable to repro today and am imagining this was related to closed issues such as #158 #144 #151 #41 etc. Closing for now.
